- id: toggle_landing_light
  alias: Toggle Landing Light Finish Dash
  trigger:
  - platform: webhook
    webhook_id: toggle_landing_light
  - event_data: {}
    event_type: finish_dash_button_pressed
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.front_landing
    service: light.toggle
  - data:
      message: Landing light switched on via dash button
    service: notify.homeassistant
  initial_state: true

- id: toggle_hallway_light
  alias: Toggle Hallway Light Andrex Dash
  trigger:
  - platform: webhook
    webhook_id: toggle_hallway_light
  - event_data: {}
    event_type: andrex_dash_button_pressed
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.hallway
    service: light.toggle
  - data:
      message: Hallway light switched on via dash button
    service: notify.homeassistant
  initial_state: true

- id: toggle_master_bedroom_light
  alias: Toggle Master Bedroom Light Ariel Dash
  trigger:
  - event_data: {}
    event_type: ariel_dash_button_pressed
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.bedroom
    service: light.toggle
  - data:
      message: Bedroom light switched on via dash button
    service: notify.homeassistant
  initial_state: true

- id: toggle_dining_room_light
  alias: Toggle Dining Room Light Dettol Dash
  trigger:
  - platform: webhook
    webhook_id: toggle_dining_room_light
  - event_data: {}
    event_type: dettol_dash_button_pressed
    platform: event
  condition: []
  action:
  - data:
      entity_id: switch.dining_room_ceiling
    service: switch.toggle
  - data:
      message: Dining room light switched on via dash button
    service: notify.homeassistant
  initial_state: true

- id: weekdays_heating_on
  alias: Weekdays Heating On
  trigger:
  - at: 05:00:00
    platform: time
  - at: '16:00:00'
    platform: time
  - at: '20:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - group.heating
    service: switch.turn_on
  - data:
      message: Heating switched on by homeassistant according to weekday schedule
    service: notify.homeassistant
  initial_state: false

- id: weekdays_heating_off
  alias: Weekdays Heating Off
  trigger:
  - at: 09:00:00
    platform: time
  - at: '18:00:00'
    platform: time
  - at: '22:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id:
      - group.heating
    service: switch.turn_off
  - data:
      message: Heating switched off by homeassistant according to weekday schedule
    service: notify.homeassistant
  initial_state: false

- id: weekends_heating_on
  alias: Weekends Heating On
  trigger:
  - at: 08:00:00
    platform: time
  - at: '14:00:00'
    platform: time
  - at: '20:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id:
      - group.heating
    service: switch.turn_on
  - data:
      message: Heating switched on by homeassistant according to weekend schedule
    service: notify.homeassistant
  initial_state: false

- id: weekends_heating_off
  alias: Weekends Heating Off
  trigger:
  - at: '11:00:00'
    platform: time
  - at: '17:00:00'
    platform: time
  - at: '22:00:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id:
      - group.heating
    service: switch.turn_off
  - data:
      message: Heating switched off by homeassistant according to weekend schedule
    service: notify.homeassistant
  initial_state: false

- id: '1545371565523'
  alias: Turn Porch Light On At 4PM
  trigger:
  - at: '16:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.porch_outdoor_light
    service: light.turn_on
  initial_state: true

- id: '1545371589939'
  alias: Turn Porch Light Off At 10:30PM
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.porch_outdoor_light
    service: light.turn_off
  initial_state: true

- id: '1545429145548'
  alias: Dyson Fan On Schedule
  trigger:
  - at: 02:00:00
    platform: time
  - at: '10:00:00'
    platform: time
  - at: '18:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: fan.hallway
    service: fan.turn_on
  - data:
      entity_id: fan.hallway
      speed: auto
    service: fan.set_speed
  - data:
      entity_id: fan.hallway
      oscillating: true
    service: fan.oscillate
  initial_state: true

- id: '1545429935532'
  alias: Dyson Fan Off Schedule
  trigger:
  - at: 06:00:00
    platform: time
  - at: '12:00:00'
    platform: time
  - at: '20:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: fan.hallway
    service: fan.turn_off
  initial_state: true

- id: '1545430945695'
  alias: Flash colours in living room at 3:30am so Andrew goes to bed
  trigger:
  - at: 03:30:00
    platform: time
  - platform: webhook
    webhook_id: living_room_flashing_warning
  - at: 03:45:00
    platform: time
  condition: []
  action:
  - data:
      brightness_pct: 100
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: blue
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: red
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      color_name: papayawhip
      entity_id: light.living_room_uplighter
    service: light.turn_on
  - delay: '1'
  - data:
      entity_id: light.living_room_uplighter
    service: light.turn_off
  initial_state: true

- id: save_power_at_night
  alias: Save Power at 1am
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id:
      - group.all_shared_spaces
    service: homeassistant.turn_off
  - data:
      message: All shared spaces switched off by homeassistant to save power
    service: notify.homeassistant

