homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 52
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:
  javascript_version: latest

lovelace:
  mode: yaml

custom_updater:
  track:
    - cards
    - components

python_script:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://home.beveridge.uk
  server_port: 8123
  api_password: !secret http_api_password
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
  trusted_networks:
    - 127.0.0.1
    - 172.16.0.0/12
    - 192.168.0.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  db_url: !secret cloud_sql_postgresql

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:account-multiple
  - name: Work (M)
    latitude: 55.952003
    longitude: -3.204456
    radius: 100
    icon: mdi:worker

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

#mqtt:
#  broker: 192.168.0.15
#  client_id: hassmqttclient

group: !include_dir_merge_named groups
scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: GB
  devices:
    - device_id: !secret dyson_serial
      device_ip: 192.168.0.50

light:
  - platform: tplink
    host: 192.168.0.29

sensor:
  - platform: loopenergy
    electricity:
      electricity_serial: !secret loopenergy_serial
      electricity_secret: !secret loopenergy_secret
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity
      - light
binary_sensor:
  - platform: wirelesstag
    monitored_conditions:
      - motion
      - battery

notify:
  - platform: slack
    name: 'slack'
    api_key: 'xoxb-106807445399-528202600182-xvYyeJBWYr9uBzrzQBv1GZg8'
    default_channel: '#bots'

device_tracker:
  - platform: google_maps
    username: beveridgehomeassistant@gmail.com
    password: !secret beveridgehome_google_password

# This enables the Cloud-based Tuya integration, which only works when internet is available.
# Since we're controlling our heating and some of the lights via Tuya devices, this isn't acceptable.
#tuya:
#   username: !secret tuya_username
#   password: !secret tuya_password
#   country_code: 44
#   platform: smart_life

# Instead, we've replaced this with the local pytuya-based version below, from https://github.com/slomanl1/tuya-homeassistant 

switch:
  - platform: tuyalocal
    name: Kettle
    host: 192.168.0.60
    local_key: !secret smart_plug_1_local_key
    device_id: !secret smart_plug_1_device_id
# Commented out as this smart plug is currently disconnected due to not needing smart switch here and it confusing guests
#  - platform: tuyalocal
#    name: Guest Fan Heater
#    host: 192.168.0.61
#    local_key: !secret smart_plug_2_local_key 
#    device_id: !secret smart_plug_2_device_id 
  - platform: tuyalocal
    name: TV Corner
    host: 192.168.0.62
    local_key: !secret smart_plug_3_local_key 
    device_id: !secret smart_plug_3_device_id 
# Commented out as these smart plugs are currently disconnected/unused
#  - platform: tuyalocal
#    name: Desk Corner
#    host: 192.168.0.63
#    local_key: !secret smart_plug_4_local_key 
#    device_id: !secret smart_plug_4_device_id 
#  - platform: tuyalocal
#    name: Smart Plug 5
#    host: 192.168.0.64
#    local_key: !secret smart_plug_5_local_key 
#    device_id: !secret smart_plug_5_device_id 
#  - platform: tuyalocal
#    name: Smart Plug 6
#    host: 192.168.0.65
#    local_key: !secret smart_plug_6_local_key 
#    device_id: !secret smart_plug_6_device_id 
  - platform: tuyalocal
    name: Heating
    host: 192.168.0.66
    local_key: !secret smart_plug_7_local_key 
    device_id: !secret smart_plug_7_device_id 
# Commented out as this smart plug is currently disconnected/unused due to boiler not needing to ever be switched off
#  - platform: tuyalocal
#    name: Boiler
#    host: 192.168.0.67
#    local_key: !secret smart_plug_8_local_key 
#    device_id: !secret smart_plug_8_device_id 
  - platform: tuyalocal
    name: Dining Room Ceiling
    host: 192.168.0.69
    local_key: !secret sonoff_tuya_1_local_key 
    device_id: !secret sonoff_tuya_1_device_id 
  - platform: sonoff_lan_mode
    name: Kitchen Ceiling
    host: 192.168.0.72
    icon: mdi:bulb

google_assistant:
  project_id: beveridge-homeassistant
  api_key: !secret google_homegraph_api_key
  expose_by_default: false
  exposed_domains:
    - switch
    - light
    - fan
    - group
    - scene
    - script
  entity_config:
    group.living_room:
      expose: true
    group.dining_room:
      expose: true
    light.bedroom:
      expose: true
      name: Bedroom Lights
    light.hallway:
      expose: true
      name: Hallway Light
    light.front_landing:
      expose: true
      name: Landing Light
    group.heating:
      expose: true
    light.living_room:
      expose: true
      name: Living Room Lights
    script.heating_boost:
      expose: true
      name: Heating Boost
    scene.living_room_low:
      expose: true
      name: Living Room Low
    scene.living_room_medium:
      expose: true
      name: Living Room Medium
    scene.living_room_high:
      expose: true
      name: Living Room High

wirelesstag:
  username: !secret wirelesstag_username
  password: !secret wirelesstag_password

