homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 52
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

lovelace:
  mode: yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   base_url: !secret http_base_url
   ssl_certificate: /data/data/com.termux/files/home/.homeassistant/sslfullchain.pem
   ssl_key: /data/data/com.termux/files/home/.homeassistant/sslprivkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

tuya:
   username: !secret tuya_username
   password: !secret tuya_password
   country_code: 44
   platform: smart_life

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: GB
  devices:
    - device_id: dyson_serial
      device_ip: 192.168.0.50

light:
  - platform: tplink
    host: 192.168.0.29

sensor:
  - platform: loopenergy
    electricity:
      electricity_serial: !secret loopenergy_serial
      electricity_secret: !secret loopenergy_secret

notify:
  - name: homeassistant
    platform: pushbullet
    api_key: !secret pushbullet_api_key

device_tracker:
  - platform: google_maps
    username: beveridgehomeassistant@gmail.com
    password: !secret beveridgehome_google_password

group:
    living_room:
      name: Living Room
      entities:
        - light.living_room
        - switch.living_room_desk_corner
        - switch.living_room_tv_corner
    dining_room:
      name: Dining Room
      entities:
        - switch.dining_room_ceiling
    bedroom:
      name: Bedroom
      entities:
        - light.bedroom
    hallway:
      name: Hallway
      entities:
        - light.hallway
        - light.front_landing

