title: Beveridge Home
resources:
  - url: /local/stylesheet.css?v=6
    type: css
views:
  - title: Home
    path: home
    cards:
      - type: glance
        columns: 4
        entities:
          - entity: device_tracker.google_maps_117449761518599578465
            name: Andrew
          - entity: device_tracker.google_maps_117231704443313059675
            name: Mar
          - entity: sensor.hallway_temperature
            name: Temperature
          - entity: sensor.power_usage
            name: Electricity
          - entity: script.heating_boost
            name: Boost Heat
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: script.heating_boost
          - entity: switch.kettle
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: switch.kettle
          - entity: group.heating
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.heating
          - entity: fan.hallway
            name: Air Purifier
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: fan.hallway
      - type: picture-glance
        image: /local/living_room.png
        title: Living room
        tap_action:
          action: call-service
          service: homeassistant.toggle
          service_data:
            entity_id: group.living_room
        entities:
          - entity: scene.living_room_low
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: scene.living_room_medium
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: scene.living_room_high
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: light.living_room
          - entity: group.living_room_switches
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.living_room_switches
      - type: picture-glance
        image: /local/dining_room.png
        title: Dining room
        entities:
          - entity: switch.dining_room_ceiling
      - type: picture-glance
        image: /local/hallway.png
        title: Hallway
        entities:
          - entity: scene.hallway_low
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: scene.hallway_medium
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: scene.hallway_high
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: light.hallway
      - type: picture-glance
        image: /local/master_bedroom.png
        title: Bedroom
        entities:
          - entity: scene.bedroom_low
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: scene.bedroom_medium
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: scene.bedroom_high
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: light.bedroom
      - type: history-graph
        title: Heating
        entities:
          - entity: sensor.hallway_temperature
            name: Temperature
          - entity: sensor.power_usage
            name: Power Usage
      - type: history-graph
        title: 'Air Quality'
        entities:
          - entity: fan.hallway
            name: Purifier
          - entity: sensor.hallway_particulate_matter_25_gm3
            name: PM2.5
          - entity: sensor.hallway_particulate_matter_10_gm3
            name: PM10
          - entity: sensor.hallway_volatile_organic_compounds
            name: VOCs
          - entity: sensor.hallway_nitrogen_dioxide
            name: NO2
          - entity: sensor.hallway_humidity
            name: Humidity
            
  - title: Automation
    path: automation
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - group.all_automations

      - type: entities
        title: Groups
        show_header_toggle: false
        entities:
          - group.all_automations
          - group.all_devices
          - group.all_fans
          - group.all_lights
          - group.all_scripts
          - group.all_switches

