title: 'Beveridge Home'
resources:
  - url: /local/card-tools.js?v=5e7654
    type: js
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/vertical-stack-in-card.js?v=0.0.9
    type: js
  - url: /local/monster-card.js?v=0.2.3
    type: js
  - url: /local/layout-card.js?v=bd7e5a
    type: js
  - url: /local/card-modder.js?v=0
    type: js
views:
  - title: 'Home'
    path: home
    cards:
      - type: custom:vertical-stack-in-card
        cards:
          - type: picture-glance
            title: 'Living room'
            state_image:
              "on": /local/living_room.png
              "off": /local/living_room_dark.png
            entity: group.living_room
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.living_room
            entities:
              - entity: scene.living_room_off
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_off
              - entity: scene.living_room_low
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_low
              - entity: scene.living_room_medium
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_medium
              - entity: scene.living_room_high
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_room_high

          - type: picture-glance
            title: 'Kitchen'
            state_image:
              "on": /local/kitchen.png
              "off": /local/kitchen_dark.png
            entity: group.dining_room
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.dining_room
            entities:
              - entity: scene.dining_room_off
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.dining_room_off

          - type: picture-glance
            title: 'Dining room'
            state_image:
              "on": /local/dining_room.png
              "off": /local/dining_room_dark.png
            entity: group.dining_room
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.dining_room
            entities:
              - entity: scene.dining_room_off
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.dining_room_off

          - type: picture-glance
            title: 'Hallway'
            state_image:
              "on": /local/hallway.png
              "off": /local/hallway_dark.png
            entity: group.hallway
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.hallway
            entities:
              - entity: scene.hallway_off
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.hallway_off
              - entity: scene.hallway_low
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.hallway_low
              - entity: scene.hallway_medium
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.hallway_medium
              - entity: scene.hallway_high
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.hallway_high

          - type: picture-glance
            title: 'Bedroom'
            state_image:
              "on": /local/master_bedroom.png
              "off": /local/master_bedroom_dark.png
            entity: group.bedroom
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.bedroom
            entities:
              - entity: scene.bedroom_off
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bedroom_off
              - entity: scene.bedroom_low
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bedroom_low
              - entity: scene.bedroom_medium
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bedroom_medium
              - entity: scene.bedroom_high
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.bedroom_high

#          - type: picture-elements
#            image: /local/hallway.png
#            elements:
#              - type: state-icon
#                style: {left: 66%, top: 80%, --paper-item-icon-color: white}
#                entity: scene.hallway_off
#                tap_action:
#                  action: call-service
#                  service: scene.turn_on
#                  service_data:
#                    entity_id: scene.hallway_off
#                
#              - type: state-icon
#                style: {left: 75%, top: 80%, --paper-item-icon-color: white}
#                entity: scene.hallway_low
#                tap_action:
#                  action: call-service
#                  service: scene.turn_on
#                  service_data:
#                    entity_id: scene.hallway_low
#                    
#              - type: state-icon
#                style: {left: 84%, top: 80%, --paper-item-icon-color: white}
#                entity: scene.hallway_medium
#                tap_action:
#                  action: call-service
#                  service: scene.turn_on
#                  service_data:
#                    entity_id: scene.hallway_medium
#                    
#              - type: state-icon
#                style: {left: 93%, top: 80%, --paper-item-icon-color: white}
#                entity: scene.hallway_high
#                tap_action:
#                  action: call-service
#                  service: scene.turn_on
#                  service_data:
#                    entity_id: scene.hallway_high


      - type: vertical-stack
        cards:
          - type: custom:vertical-stack-in-card
            title: 'Heating'
            cards:
              - type: glance
                columns: 4
                entities:
                  - entity: sensor.wirelesstag_hallway_temperature
                    name: 'Temperature'
                  - entity: script.heating_boost
                    name: '3 Hour Boost'
                    tap_action:
                      action: call-service
                      service: homeassistant.toggle
                      service_data:
                        entity_id: script.heating_boost
                  - entity: switch.boiler
                    name: 'Heating'
                    tap_action:
                      action: call-service
                      service: homeassistant.toggle
                      service_data:
                        entity_id: group.heating
                  - entity: sensor.power_usage
                    name: 'Electricity'
                  - entity: automation.weekdays_heating_on
                    tap_action:
                      action: call-service
                      service: homeassistant.toggle
                      service_data:
                        entity_id: automation.weekdays_heating_on
                  - entity: automation.weekdays_heating_off
                    tap_action:
                      action: call-service
                      service: homeassistant.toggle
                      service_data:
                        entity_id: automation.weekdays_heating_off
                  - entity: automation.weekends_heating_on
                    tap_action:
                      action: call-service
                      service: homeassistant.toggle
                      service_data:
                        entity_id: automation.weekends_heating_on
                  - entity: automation.weekends_heating_off
                    tap_action:
                      action: call-service
                      service_data:
                        entity_id: automation.weekends_heating_off
                      service: homeassistant.toggle
    
              - type: history-graph
                entities:
                  - entity: group.heating
                  - entity: sensor.wirelesstag_hallway_temperature
                    name: 'Hallway'
                  - entity: sensor.wirelesstag_living_room_temperature
                    name: 'Living Room'
                  - entity: sensor.wirelesstag_bedroom_temperature
                    name: 'Bedroom'
            
      - type: custom:vertical-stack-in-card
        title: 'Power Usage'
        cards:
          - type: glance
            columns: 4
            entities:
              - entity: device_tracker.google_maps_117449761518599578465
                name: 'Andrew'
              - entity: device_tracker.google_maps_117231704443313059675
                name: 'Mar'
              - entity: switch.kettle
                tap_action:
                  action: call-service
                  service: homeassistant.toggle
                  service_data:
                    entity_id: switch.kettle
              - entity: group.all_shared_spaces
                name: Save Power
                icon: mdi:sleep
                tap_action:
                  action: call-service
                  service: homeassistant.turn_off
                  service_data:
                    entity_id: group.all_shared_spaces
          - type: history-graph
            entities:
              - entity: sensor.power_usage
                name: 'Power Usage'

      - type: custom:vertical-stack-in-card
        title: 'Air Quality'
        cards:
          - type: glance
            columns: 4
            show_state: false
            entities:
              - entity: script.fan_off
                name: 'Off'
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.fan_off
              - entity: script.fan_auto
                name: 'Auto'
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.fan_auto
              - entity: script.fan_max
                name: 'Max'
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.fan_max
              - entity: fan.hallway
                name: 'Purifier'

          - type: history-graph
            entities:
              - entity: fan.hallway
                name: 'Purifier'

          - type: history-graph
            entities:
              - entity: sensor.hallway_particulate_matter_25_gm3
                name: 'PM2.5'
              - entity: sensor.hallway_particulate_matter_10_gm3
                name: 'PM10'

          - type: history-graph
            entities:
              - entity: sensor.hallway_volatile_organic_compounds
                name: 'VOCs'
              - entity: sensor.hallway_nitrogen_dioxide
                name: 'NO2'
              - entity: sensor.wirelesstag_hallway_humidity
                name: 'Hallway RH'
              - entity: sensor.wirelesstag_living_room_humidity
                name: 'Living Room RH'
              - entity: sensor.wirelesstag_bedroom_humidity
                name: 'Bedroom RH'

  - title: All
    path: all
    panel: true
    cards:
    
    - type: vertical-stack
      cards:
        - type: custom:monster-card
          card:
            type: entities
            title: Lights
            columns: 10
          filter:
            include:
              - domain: light
        - type: custom:monster-card
          card:
            type: entities
            title: Switches
            columns: 10
          filter:
            include:
              - domain: switch
              - domain: fan
        - type: custom:monster-card
          card:
            type: entities
            title: Binary Sensors
            columns: 10
          filter:
            include:
              - domain: binary_sensor
        - type: custom:monster-card
          card:
            type: entities
            title: Sensors
            columns: 10
          filter:
            include:
              - domain: sensor
        - type: custom:monster-card
          card:
            type: entities
            title: Devices
            columns: 10
          filter:
            include:
              - domain: device_tracker
        - type: custom:monster-card
          card:
            type: entities
            title: Scripts
            columns: 10
          filter:
            include:
              - domain: script
        - type: custom:monster-card
          card:
            type: entities
            title: Automations
            columns: 10
          filter:
            include:
              - domain: automation
        - type: custom:tracker-card
          title:
          trackers:
            - sensor.custom_card_tracker
            - sensor.custom_component_tracker
