title: Beveridge Home
views:
  - title: Home
    path: home
    cards:
      - type: glance
        title: Summary
        entities:
          - entity: device_tracker.google_maps_117449761518599578465
            name: Andrew
          - entity: device_tracker.google_maps_117231704443313059675
            name: Mar
          - entity: sensor.hallway_temperature
            name: Temperature
          - entity: sensor.power_usage
            name: Power Usage 
            icon: mdi:flash
          - entity: script.heating_boost
            name: 3 Hour Boost
            icon: mdi:clock-fast
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: script.heating_boost
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - entity: light.living_room
            name: Living Room
          - entity: switch.dining_room_ceiling
            icon: mdi:lightbulb
            name: Dining Room
          - entity: light.bedroom
            name: Bedroom
          - entity: light.hallway
            name: Hallway
          - entity: scene.living_room_low
          - entity: scene.living_room_medium
          - entity: scene.living_room_high
      - type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - entity: switch.kettle
            name: Kettle
            icon: mdi:kettle
          - entity: group.living_room_switches
            name: Living Room Corners
            icon: mdi:power-socket-uk
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.living_room_switches
          - entity: group.heating
            name: Heating
            icon: mdi:radiator
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: group.heating
          - entity: fan.hallway
            name: Air Purifier
            icon: mdi:air-conditioner
            tap_action:
              action: call-service
              service: homeassistant.toggle
              service_data:
                entity_id: fan.hallway
      - type: history-graph
        title: Heating
        entities:
          - entity: sensor.hallway_temperature
            name: Temperature
          - entity: sensor.power_usage
            name: Power Usage
      - type: history-graph
        title: 'Air Quality'
        entities:
          - entity: fan.hallway
            name: Purifier
          - entity: sensor.hallway_particulate_matter_25_gm3
            name: PM2.5
          - entity: sensor.hallway_particulate_matter_10_gm3
            name: PM10
          - entity: sensor.hallway_volatile_organic_compounds
            name: VOCs
          - entity: sensor.hallway_nitrogen_dioxide
            name: NO2
          - entity: sensor.hallway_humidity
            name: Humidity
      - type: map
        title: Locations
        aspect_ratio: 16x9
        default_zoom: 8
        entities:
          - entity: device_tracker.google_maps_117449761518599578465
          - entity: device_tracker.google_maps_117231704443313059675
          - entity: zone.home

  - title: Automation
    path: automation
    cards:
      - type: entities
        title: Automations
        show_header_toggle: false
        entities:
          - group.all_automations

      - type: entities
        title: Groups
        show_header_toggle: false
        entities:
          - group.all_automations
          - group.all_devices
          - group.all_fans
          - group.all_lights
          - group.all_scripts
          - group.all_switches

