# Describes the format for available fan services

set_speed:
  description: Sets fan speed.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: 'fan.living_room'
    speed:
      description: Speed setting
      example: 'low'

turn_on:
  description: Turns fan on.
  fields:
    entity_id:
      description: Names(s) of the entities to turn on
      example: 'fan.living_room'
    speed:
      description: Speed setting
      example: 'high'

turn_off:
  description: Turns fan off.
  fields:
    entity_id:
      description: Names(s) of the entities to turn off
      example: 'fan.living_room'

oscillate:
  description: Oscillates the fan.
  fields:
    entity_id:
      description: Name(s) of the entities to oscillate
      example: 'fan.desk_fan'
    oscillating:
      description: Flag to turn on/off oscillation
      example: True

toggle:
  description: Toggle the fan on/off.
  fields:
    entity_id:
      description: Name(s) of the entities to toggle
      exampl: 'fan.living_room'

set_direction:
  description: Set the fan rotation.
  fields:
    entity_id:
      description: Name(s) of the entities to toggle
      example: 'fan.living_room'
    direction:
      description: The direction to rotate. Either 'forward' or 'reverse'
      example: 'forward'

dyson_set_night_mode:
  description: Set the fan in night mode.
  fields:
    entity_id:
      description: Name(s) of the entities to enable/disable night mode
      example: 'fan.living_room'
    night_mode:
      description: Night mode status
      example: true

dyson_set_auto_mode:
  description: Set the fan in auto mode.
  fields:
    entity_id:
      description: Name(s) of the entities to enable/disable auto mode
      example: 'fan.living_room'
    auto_mode:
      description: Auto mode status
      example: true

dyson_set_angle:
  description: Set the oscillation angle of the selected fan(s).
  fields:
    entity_id:
      description: Name(s) of the entities for which to set the an gle
      example: 'fan.living_room'
    angle_low:
      description: The angle at which the oscillation should start
      example: 1
    angle_high:
      description: The angle at which the oscillation should end
      example: 255

dyson_flow_direction_front:
  description: Set the fan flow directio0n.
  fields:
    entity_id:
      description: Name(s) of the entities to set frontal flow direction for
      example: 'fan.living_room'
    flow_direction_front:
      description: Frontal flow direction
      example: true

dyson_set_timer:
  description: Set the sleep timer.
  fields:
    entity_id:
      description: Name(s) of the entities to set the sleep timer for
      example: 'fan.living_room'
    timer:
      description: Timer status
      example: 30

xiaomi_miio_set_buzzer_on:
  description: Turn the buzzer on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_buzzer_off:
  description: Turn the buzzer off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_led_on:
  description: Turn the led on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_led_off:
  description: Turn the led off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_child_lock_on:
  description: Turn the child lock on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_child_lock_off:
  description: Turn the child lock off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_favorite_level:
  description: Set the favorite level.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'
    level:
      description: Level, between 0 and 16.
      example: 1

xiaomi_miio_set_led_brightness:
  description: Set the led brightness.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'
    brightness:
      description: Brightness (0 = Bright, 1 = Dim, 2 = Off)
      example: 1

xiaomi_miio_set_auto_detect_on:
  description: Turn the auto detect on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_auto_detect_off:
  description: Turn the auto detect off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_learn_mode_on:
  description: Turn the learn mode on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_learn_mode_off:
  description: Turn the learn mode off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_volume:
  description: Set the sound volume.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'
    volume:
      description: Volume, between 0 and 100.
      example: 50

xiaomi_miio_reset_filter:
  description: Reset the filter lifetime and usage.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_extra_features:
  description: Manipulates a storage register which advertises extra features. The Mi Home app evaluates the value. A feature called "turbo mode" is unlocked in the app on value 1.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'
    features:
      description: Integer, known values are 0 (default) and 1 (turbo mode).
      example: 1

xiaomi_miio_set_target_humidity:
  description: Set the target humidity.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'
    humidity:
      description: Target humidity. Allowed values are 30, 40, 50, 60, 70 and 80.
      example: 50

xiaomi_miio_set_dry_on:
  description: Turn the dry mode on.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

xiaomi_miio_set_dry_off:
  description: Turn the dry mode off.
  fields:
    entity_id:
      description: Name of the xiaomi miio entity.
      example: 'fan.xiaomi_miio_device'

wemo_set_humidity:
  description: Set the target humidity of WeMo humidifier devices.
  fields:
    entity_id:
      description: Names of the WeMo humidifier entities (0 or more entities, if no entity_id is provided, all WeMo humidifiers will have the target humidity set).
      example: 'fan.wemo_humidifier'
    target_humidity:
      description: Target humidity. This is a float value between 0 and 100, but will be mapped to the humidity levels that WeMo humidifiers support (45, 50, 55, 60, and 100/Max) by rounding the value down to the nearest supported value.
      example: 56.5
