esphomeyaml:
  name: dining_room_ceiling
  platform: ESP8266
  board: esp01_1m

# Connect to home wifi, assign static IP (pinned to MAC address in router settings)
wifi:
  ssid: 'BeveridgeHome'
  password: 'Beveridge17'
  manual_ip:
    static_ip: 192.168.0.69
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant native / binary API
api:

# Enable the built-in webserver for direct control
web_server:
  port: 80

# Allow updating firmware over the network
ota:

# Define switches / sensors / GPIO
switch:
  - platform: gpio
    pin: 4
    name: "Dining Room Ceiling"

sensor:
  - platform: hlw8012
    sel_pin: 3
    cf_pin: 5
    cf1_pin: 14
    current:
      name: "HLW8012 Current"
    voltage:
      name: "HLW8012 Voltage"
    power:
      name: "HLW8012 Power"
    update_interval: 60s
    voltage_divider: 1500
    current_resistor: 0.010