- alias: Activate Living Room Switches When Light On
  trigger:
    platform: state
    entity_id: light.living_room
    to: 'on'
  condition:
    - condition: state
      entity_id: group.living_room_switches
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_room_switches
    - service: notify.homeassistant
      data:
        message: Living room corners switched on by lights